version: '3.7'
services:
  db:
    image: postgres:9.5.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - db:db
    depends_on:
      - db
volumes:
  postgres_data: