version: '3.7'
services:
  db:
    image: postgres:9.5.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - web-variables.env
volumes:
  postgres_data: